### ISSUE TITLE
Assert correct return value from required_user functions

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides3-autoupdate-service#157] opened 2021-04-06 07:53 UTC
(Follow-up from #122)

The problem was this: The function tried to access a field which didn't exist, did not throw an error but instead set this field to `0`. This lead to the whole function returning `0` as a required user. It surprises me that the rest of the code did not crash when handling this, but nevertheless it should be checked to see that this doesn't happen. Some suggestions:
- Explicitely check that the fields you try to parse from the JSON objects are actually there. If I understood it correctly, `0` is the null value for golang which kind of conflicts with our logic if it is assumed to be a valid value.
- Explicitely check after calling any required_user function that the return value is not `0`
- Write explicit unit tests for this case

From @FinnStutzenstein:
> I wonder, why the code receiving a user id 0 from the required function works - this needs to be checked too. I would expect, that something must fail there trying to access an invalid user.

**Comment by ostcar** [comment] 2021-05-23 10:59
@jsangmeister I see that this is a problem but your bug report is to abstract for me. I can not go throw all the code and look for situations like this.

Can you tell me situations when this happens? If not, then I would say we close this issue and open new issues with concrete bug reports as soon as say appear.

**Comment by jsangmeister** [comment] 2021-05-25 15:48
The situation where this happened was removed because the code was obsolet (or, to be more specific, unneeded in the first place). But at least the latter suggestions above are directed at the general handling of these functions: E.g. you can check in the generic code for handling required_user functions that the return value is not `0` and write an explicit unit test for this case. The first bullet point is more general, but I think is important for all unmarshalling of JSON objects, which is done all the time as far as I see it: If you try to access a field which is not there, an error should be thrown, because either the programmer did something wrong or invalid data was sent. In python the equivalent would be direct member access (`dict["field"]` will throw an error if `field` does not exist on `dict`), which can be used on all required fields.

I think this is a more general issue, so it does not make sense to point to specific situations here.

**Comment by ostcar** [comment] 2021-05-26 07:02
For me the OS3 autoupdate service is just temporary. I don't do any cleanups if there is no concrete bug.

Of cause, you can fix this if you want. I will only do it, if you find a bug that you can reproduce by sending data from the outside of the service.

**Comment by ostcar** [comment] 2021-07-23 07:55
Since nobody is doing this, I close this here

**Closed by ostcar** 2021-07-23 07:55 UTC
Labels: needs information
